# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f41bb37ebfead1faaaaaf68ec351e179e39c42f31e3d79cc3490eadcc6b7de4c63b4b58560969987bfd210acbb092f08ef4813d9550979ee68a3b58c61ceb86

test:
  secret_key_base: 321ab3af283655c9f4ff99028320eb6595940963c2c55a392997c3e1e888eaf84031fa7b3e40e3ba6d7912a201605623dd4abd4441dbad780902eaf87cdac8f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
