source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'cloudinary'
gem 'rails', '~> 5.0.4'
gem 'foreman', '~> 0.84.0'
gem 'sidekiq', '~> 5.0.4'
gem 'active_model_serializers', '~> 0.10.0.rc2'
gem 'rack-cors'
gem 'carrierwave'
gem "mini_magick"
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
gem 'bcrypt', '~> 3.1.11'
# Use Puma as the app server
gem 'jwt'
gem 'puma', '~> 3.0'
gem 'simple_command'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.5.0'
end

group :development do
end

group :test do
  gem 'faker', '~> 1.8.4'
  gem 'factory_girl_rails', '~> 4.8.0'
  gem 'shoulda-matchers', '~> 3.1.2'
  gem 'database_cleaner', '~> 1.6.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
